// Code generated by "stringer -type=PageType"; DO NOT EDIT.

package ads

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PTUnknown-0]
	_ = x[PTPageUrl-1]
	_ = x[PTVideo-2]
	_ = x[PTImage-3]
	_ = x[PTText-4]
}

const _PageType_name = "PTUnknownPTPageUrlPTVideoPTImagePTText"

var _PageType_index = [...]uint8{0, 9, 18, 25, 32, 38}

func (i PageType) String() string {
	if i < 0 || i >= PageType(len(_PageType_index)-1) {
		return "PageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PageType_name[_PageType_index[i]:_PageType_index[i+1]]
}
